array_1=["pen","paper","book","bottle"];
random_no = Math.floor((Math.random()*array_1.length)+1);
Element_of_array = array_1[random_no];
sketch=Element_of_array;
console.log(sketch);
timer_counter=0;
timer_check="";
drawn_sketch="";
answer_holder="";
score=0;